name: Front CI/CD
on:
  push:
    branches: [ "main", dev/* ]
  pull_request:
    branches: [ "main",  dev/* ]

jobs:
  build-test-analyse:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - name: NPM install
      run: npm ci
    - name: Test
      run: npm test -- --watch=false --browsers=ChromeHeadless --code-coverage
    - name: Upload coverage
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: front/coverage/bobapp/
    - name: Analyze with SonarCloud
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        projectBaseDir: front
  deploy-on-docker:
    needs: build-test-analyse
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./front
          file: ./front/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-front:latest
  
