name: Back CI

on:
  push:
    branches: [ "main", dev/* ]
  pull_request:
    branches: [ "main",  dev/* ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Adem-S_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD
    - name: Upload jacoco coverage
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: back/target/site/jacoco/
