name: Front CI

on:
  push:
    branches: [ "main", dev/* ]
  pull_request:
    branches: [ "main",  dev/* ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front 
        
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - name: NPM install
      run: npm ci
    - name: Test
      run: npm test -- --watch=false --browsers=ChromeHeadless --code-coverage
    - name: Upload coverage
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: front/coverage/bobapp/
