name: Back CI

on:
  push:
    branches: [ "main", dev/* ]
  pull_request:
    branches: [ "main",  dev/* ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Test with Maven
      run: mvn -B test --file pom.xml
    - name: Upload jacoco coverage
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: back/target/site/jacoco/
    - name: Analyze with SonarCloud
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        projectBaseDir: back
