name: Back CI

on:
  push:
    branches: [ "main", dev/* ]
  pull_request:
    branches: [ "main",  dev/* ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build and analyze
      env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn clean verify sonar:sonar \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=adem-s \
          -Dsonar.projectKey=Adem-S_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD
    - name: Upload jacoco coverage
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: back/target/site/jacoco/
